version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: cae-postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SECRET}
      POSTGRES_DB: ${DB_NAME}
      # Production settings
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cae-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    # Security: Don't expose ports to host in production
    # ports:
    #   - "5432:5432"

  cae:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: cae:prod
    container_name: cae-app-prod
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      # LLM Configuration
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_API_BASE_URL: ${LLM_API_BASE_URL}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}
      EMBEDDING_MODEL_API_KEY: ${EMBEDDING_MODEL_API_KEY}
      EMBEDDING_MODEL_BASE_URL: ${EMBEDDING_MODEL_BASE_URL}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_SECRET: ${DB_SECRET}
      # Production Configuration
      LOG_LEVEL: ${LOG_LEVEL:-WARNING}
      LLM_TIMEOUT_SECONDS: ${LLM_TIMEOUT_SECONDS:-600}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cae-network
    restart: always
    volumes:
      - ./logs:/app/logs:rw
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: cae-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cae
    networks:
      - cae-network
    restart: always
    profiles:
      - with-nginx

networks:
  cae-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local 